name: agil_app
description: "Agil Distribution Tunisia - Professional Energy Distribution Platform"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  
  # Navigation
  go_router: ^14.2.7
  
  # Network & HTTP
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Local Storage & Authentication
  shared_preferences: ^2.2.2
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  
  # Database
  postgres: ^3.0.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  
  # Image Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  
  # UI Enhancement
  lottie: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/icons/
